package co.gov.dane.sipsa.backend.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ARTI_CARA_VALORES_I01".
 */
public class ArtiCaraValoresI01 {

    private Long id;
    private Long tireId;
    private Long caraId;
    private Long artiId;
    private Long grin2Id;
    private Long vapeId;
    private String vapeDescripcion;

    public ArtiCaraValoresI01() {
    }

    public ArtiCaraValoresI01(Long id) {
        this.id = id;
    }

    public ArtiCaraValoresI01(Long id, Long tireId, Long caraId, Long artiId, Long grin2Id, Long vapeId, String vapeDescripcion) {
        this.id = id;
        this.tireId = tireId;
        this.caraId = caraId;
        this.artiId = artiId;
        this.grin2Id = grin2Id;
        this.vapeId = vapeId;
        this.vapeDescripcion = vapeDescripcion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    public Long getCaraId() {
        return caraId;
    }

    public void setCaraId(Long caraId) {
        this.caraId = caraId;
    }

    public Long getArtiId() {
        return artiId;
    }

    public void setArtiId(Long artiId) {
        this.artiId = artiId;
    }

    public Long getGrin2Id() {
        return grin2Id;
    }

    public void setGrin2Id(Long grin2Id) {
        this.grin2Id = grin2Id;
    }

    public Long getVapeId() {
        return vapeId;
    }

    public void setVapeId(Long vapeId) {
        this.vapeId = vapeId;
    }

    public String getVapeDescripcion() {
        return vapeDescripcion;
    }

    public void setVapeDescripcion(String vapeDescripcion) {
        this.vapeDescripcion = vapeDescripcion;
    }

}
