package co.gov.dane.sipsa.backend.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {


    private final DaoConfig fuenteDaoConfig;
    private final DaoConfig fuenteDistritoDaoConfig;
    private final DaoConfig usuarioDaoConfig;
    private final DaoConfig observacionDaoConfig;
    private final DaoConfig observacionDistritoDaoConfig;
    private final DaoConfig recoleccionInsumoDaoConfig;
    private final DaoConfig casaComercialDaoConfig;
    private final DaoConfig articuloDaoConfig;
    private final DaoConfig articuloDistritoDaoConfig;
    private final DaoConfig informanteDaoConfig;
    private final DaoConfig fuenteArticuloDaoConfig;
    private final DaoConfig fuenteArticuloDistritoDaoConfig;
    private final DaoConfig grupoDaoConfig;
    private final DaoConfig subGrupoDaoConfig;
    private final DaoConfig unidadMedidaDaoConfig;
    private final DaoConfig presentacionDaoConfig;
    private final DaoConfig tipoRecoleccionDaoConfig;
    private final DaoConfig recoleccionDaoConfig;
    private final DaoConfig recoleccionDistritoDaoConfig;
    private final DaoConfig configuracionDaoConfig;
    private final DaoConfig principalI01DaoConfig;
    private final DaoConfig recoleccionI01DaoConfig;
    private final DaoConfig informadorI01DaoConfig;
    private final DaoConfig fuenteTireI01DaoConfig;
    private final DaoConfig articuloI01DaoConfig;
    private final DaoConfig observacionI01DaoConfig;
    private final DaoConfig caracteristicaI01DaoConfig;
    private final DaoConfig valcarapermitidosI01DaoConfig;
    private final DaoConfig artiCaraValoresI01DaoConfig;
    private final DaoConfig envioArtiCaraValoresI01DaoConfig;
    private final DaoConfig grupoInsumoI01DaoConfig;
    private final DaoConfig caracteristicaDistritoDaoConfig;

    private final FuenteDao fuenteDao;
    private final FuenteDistritoDao fuenteDistritoDao;
    private final UsuarioDao usuarioDao;
    private final ObservacionDao observacionDao;
    private final ObservacionDistritoDao observacionDistritoDao;
    private final RecoleccionInsumoDao recoleccionInsumoDao;
    private final CasaComercialDao casaComercialDao;
    private final ArticuloDao articuloDao;
    private final ArticuloDistritoDao articuloDistrtioDao;
    private final InformanteDao informanteDao;
    private final FuenteArticuloDao fuenteArticuloDao;
    private final FuenteArticuloDistritoDao fuenteArticuloDistritoDao;
    private final GrupoDao grupoDao;
    private final SubGrupoDao subGrupoDao;
    private final UnidadMedidaDao unidadMedidaDao;
    private final PresentacionDao presentacionDao;
    private final TipoRecoleccionDao tipoRecoleccionDao;
    private final RecoleccionDao recoleccionDao;
    private final RecoleccionDistritoDao recoleccionDistritoDao;
    private final ConfiguracionDao configuracionDao;
    private final PrincipalI01Dao principalI01Dao;
    private final RecoleccionI01Dao recoleccionI01Dao;
    private final InformadorI01Dao informadorI01Dao;
    private final FuenteTireI01Dao fuenteTireI01Dao;
    private final ArticuloI01Dao articuloI01Dao;
    private final ObservacionI01Dao observacionI01Dao;
    private final CaracteristicaI01Dao caracteristicaI01Dao;
    private final ValcarapermitidosI01Dao valcarapermitidosI01Dao;
    private final ArtiCaraValoresI01Dao artiCaraValoresI01Dao;
    private final EnvioArtiCaraValoresI01Dao envioArtiCaraValoresI01Dao;
    private final GrupoInsumoI01Dao grupoInsumoI01Dao;
    private final CaracteristicaDistritoDao caracteristicaDistritoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fuenteDaoConfig = daoConfigMap.get(FuenteDao.class).clone();
        fuenteDaoConfig.initIdentityScope(type);

        fuenteDistritoDaoConfig = daoConfigMap.get(FuenteDistritoDao.class).clone();
        fuenteDistritoDaoConfig.initIdentityScope(type);

        usuarioDaoConfig = daoConfigMap.get(UsuarioDao.class).clone();
        usuarioDaoConfig.initIdentityScope(type);

        observacionDaoConfig = daoConfigMap.get(ObservacionDao.class).clone();
        observacionDaoConfig.initIdentityScope(type);

        observacionDistritoDaoConfig = daoConfigMap.get(ObservacionDistritoDao.class).clone();
        observacionDistritoDaoConfig.initIdentityScope(type);

        recoleccionInsumoDaoConfig = daoConfigMap.get(RecoleccionInsumoDao.class).clone();
        recoleccionInsumoDaoConfig.initIdentityScope(type);

        casaComercialDaoConfig = daoConfigMap.get(CasaComercialDao.class).clone();
        casaComercialDaoConfig.initIdentityScope(type);

        articuloDaoConfig = daoConfigMap.get(ArticuloDao.class).clone();
        articuloDaoConfig.initIdentityScope(type);

        articuloDistritoDaoConfig = daoConfigMap.get(ArticuloDistritoDao.class).clone();
        articuloDistritoDaoConfig.initIdentityScope(type);

        informanteDaoConfig = daoConfigMap.get(InformanteDao.class).clone();
        informanteDaoConfig.initIdentityScope(type);

        fuenteArticuloDaoConfig = daoConfigMap.get(FuenteArticuloDao.class).clone();
        fuenteArticuloDaoConfig.initIdentityScope(type);

        fuenteArticuloDistritoDaoConfig = daoConfigMap.get(FuenteArticuloDistritoDao.class).clone();
        fuenteArticuloDistritoDaoConfig.initIdentityScope(type);

        grupoDaoConfig = daoConfigMap.get(GrupoDao.class).clone();
        grupoDaoConfig.initIdentityScope(type);

        subGrupoDaoConfig = daoConfigMap.get(SubGrupoDao.class).clone();
        subGrupoDaoConfig.initIdentityScope(type);

        unidadMedidaDaoConfig = daoConfigMap.get(UnidadMedidaDao.class).clone();
        unidadMedidaDaoConfig.initIdentityScope(type);

        presentacionDaoConfig = daoConfigMap.get(PresentacionDao.class).clone();
        presentacionDaoConfig.initIdentityScope(type);

        tipoRecoleccionDaoConfig = daoConfigMap.get(TipoRecoleccionDao.class).clone();
        tipoRecoleccionDaoConfig.initIdentityScope(type);

        recoleccionDaoConfig = daoConfigMap.get(RecoleccionDao.class).clone();
        recoleccionDaoConfig.initIdentityScope(type);

        recoleccionDistritoDaoConfig = daoConfigMap.get(RecoleccionDistritoDao.class).clone();
        recoleccionDistritoDaoConfig.initIdentityScope(type);

        configuracionDaoConfig = daoConfigMap.get(ConfiguracionDao.class).clone();
        configuracionDaoConfig.initIdentityScope(type);

        principalI01DaoConfig = daoConfigMap.get(PrincipalI01Dao.class).clone();
        principalI01DaoConfig.initIdentityScope(type);

        recoleccionI01DaoConfig = daoConfigMap.get(RecoleccionI01Dao.class).clone();
        recoleccionI01DaoConfig.initIdentityScope(type);

        informadorI01DaoConfig = daoConfigMap.get(InformadorI01Dao.class).clone();
        informadorI01DaoConfig.initIdentityScope(type);

        fuenteTireI01DaoConfig = daoConfigMap.get(FuenteTireI01Dao.class).clone();
        fuenteTireI01DaoConfig.initIdentityScope(type);

        articuloI01DaoConfig = daoConfigMap.get(ArticuloI01Dao.class).clone();
        articuloI01DaoConfig.initIdentityScope(type);

        observacionI01DaoConfig = daoConfigMap.get(ObservacionI01Dao.class).clone();
        observacionI01DaoConfig.initIdentityScope(type);

        caracteristicaI01DaoConfig = daoConfigMap.get(CaracteristicaI01Dao.class).clone();
        caracteristicaI01DaoConfig.initIdentityScope(type);

        caracteristicaDistritoDaoConfig = daoConfigMap.get(CaracteristicaDistritoDao.class).clone();
        caracteristicaDistritoDaoConfig.initIdentityScope(type);

        valcarapermitidosI01DaoConfig = daoConfigMap.get(ValcarapermitidosI01Dao.class).clone();
        valcarapermitidosI01DaoConfig.initIdentityScope(type);

        artiCaraValoresI01DaoConfig = daoConfigMap.get(ArtiCaraValoresI01Dao.class).clone();
        artiCaraValoresI01DaoConfig.initIdentityScope(type);

        envioArtiCaraValoresI01DaoConfig = daoConfigMap.get(EnvioArtiCaraValoresI01Dao.class).clone();
        envioArtiCaraValoresI01DaoConfig.initIdentityScope(type);

        grupoInsumoI01DaoConfig = daoConfigMap.get(GrupoInsumoI01Dao.class).clone();
        grupoInsumoI01DaoConfig.initIdentityScope(type);

        fuenteDao = new FuenteDao(fuenteDaoConfig, this);
        fuenteDistritoDao = new FuenteDistritoDao(fuenteDistritoDaoConfig, this);
        usuarioDao = new UsuarioDao(usuarioDaoConfig, this);
        observacionDao = new ObservacionDao(observacionDaoConfig, this);
        observacionDistritoDao = new ObservacionDistritoDao(observacionDistritoDaoConfig, this);
        recoleccionInsumoDao = new RecoleccionInsumoDao(recoleccionInsumoDaoConfig, this);
        casaComercialDao = new CasaComercialDao(casaComercialDaoConfig, this);
        articuloDao = new ArticuloDao(articuloDaoConfig, this);
        articuloDistrtioDao = new ArticuloDistritoDao(articuloDistritoDaoConfig, this);
        informanteDao = new InformanteDao(informanteDaoConfig, this);
        fuenteArticuloDao = new FuenteArticuloDao(fuenteArticuloDaoConfig, this);
        fuenteArticuloDistritoDao = new FuenteArticuloDistritoDao(fuenteArticuloDistritoDaoConfig, this);
        grupoDao = new GrupoDao(grupoDaoConfig, this);
        subGrupoDao = new SubGrupoDao(subGrupoDaoConfig, this);
        unidadMedidaDao = new UnidadMedidaDao(unidadMedidaDaoConfig, this);
        presentacionDao = new PresentacionDao(presentacionDaoConfig, this);
        tipoRecoleccionDao = new TipoRecoleccionDao(tipoRecoleccionDaoConfig, this);
        recoleccionDao = new RecoleccionDao(recoleccionDaoConfig, this);
        recoleccionDistritoDao = new RecoleccionDistritoDao(recoleccionDistritoDaoConfig, this);
        configuracionDao = new ConfiguracionDao(configuracionDaoConfig, this);
        principalI01Dao = new PrincipalI01Dao(principalI01DaoConfig, this);
        recoleccionI01Dao = new RecoleccionI01Dao(recoleccionI01DaoConfig, this);
        informadorI01Dao = new InformadorI01Dao(informadorI01DaoConfig, this);
        fuenteTireI01Dao = new FuenteTireI01Dao(fuenteTireI01DaoConfig, this);
        articuloI01Dao = new ArticuloI01Dao(articuloI01DaoConfig, this);
        observacionI01Dao = new ObservacionI01Dao(observacionI01DaoConfig, this);
        caracteristicaI01Dao = new CaracteristicaI01Dao(caracteristicaI01DaoConfig, this);
        caracteristicaDistritoDao = new CaracteristicaDistritoDao(caracteristicaDistritoDaoConfig, this);
        valcarapermitidosI01Dao = new ValcarapermitidosI01Dao(valcarapermitidosI01DaoConfig, this);
        artiCaraValoresI01Dao = new ArtiCaraValoresI01Dao(artiCaraValoresI01DaoConfig, this);
        envioArtiCaraValoresI01Dao = new EnvioArtiCaraValoresI01Dao(envioArtiCaraValoresI01DaoConfig, this);
        grupoInsumoI01Dao = new GrupoInsumoI01Dao(grupoInsumoI01DaoConfig, this);

        registerDao(Fuente.class, fuenteDao);
        registerDao(FuenteDistrito.class, fuenteDistritoDao);
        registerDao(Usuario.class, usuarioDao);
        registerDao(Observacion.class, observacionDao);
        registerDao(ObservacionDistrito.class, observacionDistritoDao);
        registerDao(RecoleccionInsumo.class, recoleccionInsumoDao);
        registerDao(CasaComercial.class, casaComercialDao);
        registerDao(Articulo.class, articuloDao);
        registerDao(ArticuloDistrito.class, articuloDistrtioDao);
        registerDao(Informante.class, informanteDao);
        registerDao(FuenteArticulo.class, fuenteArticuloDao);
        registerDao(FuenteArticuloDistrito.class, fuenteArticuloDistritoDao);
        registerDao(Grupo.class, grupoDao);
        registerDao(SubGrupo.class, subGrupoDao);
        registerDao(UnidadMedida.class, unidadMedidaDao);
        registerDao(Presentacion.class, presentacionDao);
        registerDao(TipoRecoleccion.class, tipoRecoleccionDao);
        registerDao(Recoleccion.class, recoleccionDao);
        registerDao(RecoleccionDistrito.class, recoleccionDistritoDao);
        registerDao(Configuracion.class, configuracionDao);
        registerDao(PrincipalI01.class, principalI01Dao);
        registerDao(RecoleccionI01.class, recoleccionI01Dao);
        registerDao(InformadorI01.class, informadorI01Dao);
        registerDao(FuenteTireI01.class, fuenteTireI01Dao);
        registerDao(ArticuloI01.class, articuloI01Dao);
        registerDao(ObservacionI01.class, observacionI01Dao);
        registerDao(CaracteristicaI01.class, caracteristicaI01Dao);
        registerDao(CaracteristicaDistrito.class, caracteristicaDistritoDao);
        registerDao(ValcarapermitidosI01.class, valcarapermitidosI01Dao);
        registerDao(ArtiCaraValoresI01.class, artiCaraValoresI01Dao);
        registerDao(EnvioArtiCaraValoresI01.class, envioArtiCaraValoresI01Dao);
        registerDao(GrupoInsumoI01.class, grupoInsumoI01Dao);
    }
    
    public void clear() {
        fuenteDaoConfig.getIdentityScope().clear();
        fuenteDistritoDaoConfig.getIdentityScope().clear();
        usuarioDaoConfig.getIdentityScope().clear();
        observacionDaoConfig.getIdentityScope().clear();
        observacionDistritoDaoConfig.getIdentityScope().clear();
        recoleccionInsumoDaoConfig.getIdentityScope().clear();
        casaComercialDaoConfig.getIdentityScope().clear();
        articuloDaoConfig.getIdentityScope().clear();
        articuloDistritoDaoConfig.getIdentityScope().clear();
        informanteDaoConfig.getIdentityScope().clear();
        fuenteArticuloDaoConfig.getIdentityScope().clear();
        fuenteArticuloDistritoDaoConfig.getIdentityScope().clear();
        grupoDaoConfig.getIdentityScope().clear();
        subGrupoDaoConfig.getIdentityScope().clear();
        unidadMedidaDaoConfig.getIdentityScope().clear();
        presentacionDaoConfig.getIdentityScope().clear();
        tipoRecoleccionDaoConfig.getIdentityScope().clear();
        recoleccionDaoConfig.getIdentityScope().clear();
        recoleccionDistritoDaoConfig.getIdentityScope().clear();
        configuracionDaoConfig.getIdentityScope().clear();
        principalI01DaoConfig.getIdentityScope().clear();
        recoleccionI01DaoConfig.getIdentityScope().clear();
        informadorI01DaoConfig.getIdentityScope().clear();
        fuenteTireI01DaoConfig.getIdentityScope().clear();
        articuloI01DaoConfig.getIdentityScope().clear();
        observacionI01DaoConfig.getIdentityScope().clear();
        caracteristicaI01DaoConfig.getIdentityScope().clear();
        caracteristicaDistritoDaoConfig.getIdentityScope().clear();
        valcarapermitidosI01DaoConfig.getIdentityScope().clear();
        artiCaraValoresI01DaoConfig.getIdentityScope().clear();
        envioArtiCaraValoresI01DaoConfig.getIdentityScope().clear();
        grupoInsumoI01DaoConfig.getIdentityScope().clear();
    }

    public FuenteDao getFuenteDao() {
        return fuenteDao;
    }

    public FuenteDistritoDao getFuenteDistritoDao() {
        return fuenteDistritoDao;
    }

    public UsuarioDao getUsuarioDao() {
        return usuarioDao;
    }

    public ObservacionDao getObservacionDao() {
        return observacionDao;
    }

    public ObservacionDistritoDao getObservacionDistritoDao() {
        return observacionDistritoDao;
    }

    public RecoleccionInsumoDao getRecoleccionInsumoDao() {
        return recoleccionInsumoDao;
    }

    public CasaComercialDao getCasaComercialDao() {
        return casaComercialDao;
    }

    public ArticuloDao getArticuloDao() {
        return articuloDao;
    }

    public ArticuloDistritoDao getArticuloDistrtioDao() {
        return articuloDistrtioDao;
    }

    public InformanteDao getInformanteDao() {
        return informanteDao;
    }

    public FuenteArticuloDao getFuenteArticuloDao() {
        return fuenteArticuloDao;
    }

    public FuenteArticuloDistritoDao getFuenteArticuloDistritoDao() {
        return fuenteArticuloDistritoDao;
    }

    public GrupoDao getGrupoDao() {
        return grupoDao;
    }

    public SubGrupoDao getSubGrupoDao() {
        return subGrupoDao;
    }

    public UnidadMedidaDao getUnidadMedidaDao() {
        return unidadMedidaDao;
    }

    public PresentacionDao getPresentacionDao() {
        return presentacionDao;
    }

    public TipoRecoleccionDao getTipoRecoleccionDao() {
        return tipoRecoleccionDao;
    }

    public RecoleccionDao getRecoleccionDao() {
        return recoleccionDao;
    }

    public RecoleccionDistritoDao getRecoleccionDistritoDao() {
        return recoleccionDistritoDao;
    }

    public ConfiguracionDao getConfiguracionDao() {
        return configuracionDao;
    }

    public PrincipalI01Dao getPrincipalI01Dao() {
        return principalI01Dao;
    }

    public RecoleccionI01Dao getRecoleccionI01Dao() {
        return recoleccionI01Dao;
    }

    public InformadorI01Dao getInformadorI01Dao() {
        return informadorI01Dao;
    }

    public FuenteTireI01Dao getFuenteTireI01Dao() {
        return fuenteTireI01Dao;
    }

    public ArticuloI01Dao getArticuloI01Dao() {
        return articuloI01Dao;
    }

    public ObservacionI01Dao getObservacionI01Dao() {
        return observacionI01Dao;
    }

    public CaracteristicaDistritoDao getCaracteristicaDistritoDao() {
        return caracteristicaDistritoDao;
    }

    public CaracteristicaI01Dao getCaracteristicaI01Dao() {
        return caracteristicaI01Dao;
    }

    public ValcarapermitidosI01Dao getValcarapermitidosI01Dao() {
        return valcarapermitidosI01Dao;
    }

    public ArtiCaraValoresI01Dao getArtiCaraValoresI01Dao() {
        return artiCaraValoresI01Dao;
    }

    public EnvioArtiCaraValoresI01Dao getEnvioArtiCaraValoresI01Dao() {
        return envioArtiCaraValoresI01Dao;
    }

    public GrupoInsumoI01Dao getGrupoInsumoI01Dao() {
        return grupoInsumoI01Dao;
    }

}
