package co.gov.dane.sipsa.backend.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INFORMANTE".
 */
public class Informante {

    private Long idInformante;
    private Long idMunicipio;
    private String nombre;
    private String telefono;
    private java.util.Date fechaCreacion;
    private String usuarioCreacion;
    private java.util.Date fechaModificacion;
    private java.util.Date fechaVencimineto;

    public Informante() {
    }

    public Informante(Long idInformante) {
        this.idInformante = idInformante;
    }

    public Informante(Long idInformante, Long idMunicipio, String nombre, String telefono, java.util.Date fechaCreacion, String usuarioCreacion, java.util.Date fechaModificacion, java.util.Date fechaVencimineto) {
        this.idInformante = idInformante;
        this.idMunicipio = idMunicipio;
        this.nombre = nombre;
        this.telefono = telefono;
        this.fechaCreacion = fechaCreacion;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaModificacion = fechaModificacion;
        this.fechaVencimineto = fechaVencimineto;
    }

    public Long getIdInformante() {
        return idInformante;
    }

    public void setIdInformante(Long idInformante) {
        this.idInformante = idInformante;
    }

    public Long getIdMunicipio() {
        return idMunicipio;
    }

    public void setIdMunicipio(Long idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public java.util.Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(java.util.Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getUsuarioCreacion() {
        return usuarioCreacion;
    }

    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    public java.util.Date getFechaModificacion() {
        return fechaModificacion;
    }

    public void setFechaModificacion(java.util.Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public java.util.Date getFechaVencimineto() {
        return fechaVencimineto;
    }

    public void setFechaVencimineto(java.util.Date fechaVencimineto) {
        this.fechaVencimineto = fechaVencimineto;
    }

}
