package co.gov.dane.sipsa.backend.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INFORMADOR_I01".
 */
public class InformadorI01 {

    private Long infoId;
    private String muniId;
    private String infoNombre;
    private String infoTelefono;

    public InformadorI01() {
    }

    public InformadorI01(Long infoId) {
        this.infoId = infoId;
    }

    public InformadorI01(Long infoId, String muniId, String infoNombre, String infoTelefono) {
        this.infoId = infoId;
        this.muniId = muniId;
        this.infoNombre = infoNombre;
        this.infoTelefono = infoTelefono;
    }

    public Long getInfoId() {
        return infoId;
    }

    public void setInfoId(Long infoId) {
        this.infoId = infoId;
    }

    public String getMuniId() {
        return muniId;
    }

    public void setMuniId(String muniId) {
        this.muniId = muniId;
    }

    public String getInfoNombre() {
        return infoNombre;
    }

    public void setInfoNombre(String infoNombre) {
        this.infoNombre = infoNombre;
    }

    public String getInfoTelefono() {
        return infoTelefono;
    }

    public void setInfoTelefono(String infoTelefono) {
        this.infoTelefono = infoTelefono;
    }

    @Override
    public String toString() {
        return infoNombre ;
    }
}
