package co.gov.dane.sipsa.backend.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "OBSERVACION".
 */
public class Observacion {

    private Long obseId;
    private String obseTipo;
    private String novedad;
    private String obseDescripcion;

    public Observacion() {
    }

    public Observacion(Long obseId) {
        this.obseId = obseId;
    }

    public Observacion(Long obseId, String obseTipo, String novedad, String obseDescripcion) {
        this.obseId = obseId;
        this.obseTipo = obseTipo;
        this.novedad = novedad;
        this.obseDescripcion = obseDescripcion;
    }

    public Long getObseId() {
        return obseId;
    }

    public void setObseId(Long obseId) {
        this.obseId = obseId;
    }

    public String getObseTipo() {
        return obseTipo;
    }

    public void setObseTipo(String obseTipo) {
        this.obseTipo = obseTipo;
    }

    public String getNovedad() {
        return novedad;
    }

    public void setNovedad(String novedad) {
        this.novedad = novedad;
    }

    public String getObseDescripcion() {
        return obseDescripcion;
    }

    public void setObseDescripcion(String obseDescripcion) {
        this.obseDescripcion = obseDescripcion;
    }

}
