package co.gov.dane.sipsa.backend.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRINCIPAL_I01".
 */
public class PrincipalI01 {

    private Long id;
    private Long tireId;
    private Long futiId;
    private String muniId;
    private Long fuenId;
    private String fuenNombre;
    private Long artiId;
    private String artiNombre;
    private Long grin2Id;
    private String nombreComplemento;
    public String nombreCompleto;
    private Long artiVlrMinTomas;
    private Long artiVlrMaxTomas;
    private Long artiVlrMinRondas;
    private Long artiVlrMaxRondas;
    private Long artiVlrMinDiasm;
    private Long artiVlrMaxDiasm;
    private java.util.Date prreFechaProgramada;
    private Double promAnterior;
    private Integer fuentesCapturadas;
    private Integer estado_trasmitido;

    public PrincipalI01() {
    }

    public PrincipalI01(Long id) {
        this.id = id;
    }

    public PrincipalI01(Long id, Long tireId, Long futiId, String muniId, Long fuenId, String fuenNombre, Long artiId, String artiNombre, Long grin2Id, String nombreComplemento, Long artiVlrMinTomas, Long artiVlrMaxTomas, Long artiVlrMinRondas, Long artiVlrMaxRondas, Long artiVlrMinDiasm, Long artiVlrMaxDiasm, java.util.Date prreFechaProgramada, Double promAnterior, Integer fuentesCapturadas, Integer estado_trasmitido) {
        this.id = id;
        this.tireId = tireId;
        this.futiId = futiId;
        this.muniId = muniId;
        this.fuenId = fuenId;
        this.fuenNombre = fuenNombre;
        this.artiId = artiId;
        this.artiNombre = artiNombre;
        this.grin2Id = grin2Id;
        this.nombreComplemento = nombreComplemento;
        this.artiVlrMinTomas = artiVlrMinTomas;
        this.artiVlrMaxTomas = artiVlrMaxTomas;
        this.artiVlrMinRondas = artiVlrMinRondas;
        this.artiVlrMaxRondas = artiVlrMaxRondas;
        this.artiVlrMinDiasm = artiVlrMinDiasm;
        this.artiVlrMaxDiasm = artiVlrMaxDiasm;
        this.prreFechaProgramada = prreFechaProgramada;
        this.promAnterior = promAnterior;
        this.fuentesCapturadas = fuentesCapturadas;
        this.estado_trasmitido = estado_trasmitido;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    public Long getFutiId() {
        return futiId;
    }

    public void setFutiId(Long futiId) {
        this.futiId = futiId;
    }

    public String getMuniId() {
        return muniId;
    }

    public void setMuniId(String muniId) {
        this.muniId = muniId;
    }

    public Long getFuenId() {
        return fuenId;
    }

    public void setFuenId(Long fuenId) {
        this.fuenId = fuenId;
    }

    public String getFuenNombre() {
        return fuenNombre;
    }

    public void setFuenNombre(String fuenNombre) {
        this.fuenNombre = fuenNombre;
    }

    public Long getArtiId() {
        return artiId;
    }

    public void setArtiId(Long artiId) {
        this.artiId = artiId;
    }

    public String getArtiNombre() {
        return artiNombre;
    }

    public void setArtiNombre(String artiNombre) {
        this.artiNombre = artiNombre;
    }

    public Long getGrin2Id() {
        return grin2Id;
    }

    public void setGrin2Id(Long grin2Id) {
        this.grin2Id = grin2Id;
    }

    public String getNombreComplemento() {
        return nombreComplemento;
    }

    public void setNombreComplemento(String nombreComplemento) {
        this.nombreComplemento = nombreComplemento;
    }

    public Long getArtiVlrMinTomas() {
        return artiVlrMinTomas;
    }

    public void setArtiVlrMinTomas(Long artiVlrMinTomas) {
        this.artiVlrMinTomas = artiVlrMinTomas;
    }

    public Long getArtiVlrMaxTomas() {
        return artiVlrMaxTomas;
    }

    public void setArtiVlrMaxTomas(Long artiVlrMaxTomas) {
        this.artiVlrMaxTomas = artiVlrMaxTomas;
    }

    public Long getArtiVlrMinRondas() {
        return artiVlrMinRondas;
    }

    public void setArtiVlrMinRondas(Long artiVlrMinRondas) {
        this.artiVlrMinRondas = artiVlrMinRondas;
    }

    public Long getArtiVlrMaxRondas() {
        return artiVlrMaxRondas;
    }

    public void setArtiVlrMaxRondas(Long artiVlrMaxRondas) {
        this.artiVlrMaxRondas = artiVlrMaxRondas;
    }

    public Long getArtiVlrMinDiasm() {
        return artiVlrMinDiasm;
    }

    public void setArtiVlrMinDiasm(Long artiVlrMinDiasm) {
        this.artiVlrMinDiasm = artiVlrMinDiasm;
    }

    public Long getArtiVlrMaxDiasm() {
        return artiVlrMaxDiasm;
    }

    public void setArtiVlrMaxDiasm(Long artiVlrMaxDiasm) {
        this.artiVlrMaxDiasm = artiVlrMaxDiasm;
    }

    public java.util.Date getPrreFechaProgramada() {
        return prreFechaProgramada;
    }

    public void setPrreFechaProgramada(java.util.Date prreFechaProgramada) {
        this.prreFechaProgramada = prreFechaProgramada;
    }

    public Double getPromAnterior() {
        return promAnterior;
    }

    public void setPromAnterior(Double promAnterior) {
        this.promAnterior = promAnterior;
    }

    public Integer getFuentesCapturadas() {
        return fuentesCapturadas;
    }

    public void setFuentesCapturadas(Integer fuentesCapturadas) {
        this.fuentesCapturadas = fuentesCapturadas;
    }

    public Integer getEstado_trasmitido() {
        return estado_trasmitido;
    }

    public void setEstado_trasmitido(Integer estado_trasmitido) {
        this.estado_trasmitido = estado_trasmitido;
    }

}
