package co.gov.dane.sipsa.backend.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUP_VALOR_ESP_ANT".
 */
public class SupValorEspAnt {

    private Integer idPeriodoRecoleccion;
    private Integer idFuenteElemento;
    private Integer idElementoTipoEspecificacion;
    private String valor;

    public SupValorEspAnt() {
    }

    public SupValorEspAnt(Integer idPeriodoRecoleccion, Integer idFuenteElemento, Integer idElementoTipoEspecificacion, String valor) {
        this.idPeriodoRecoleccion = idPeriodoRecoleccion;
        this.idFuenteElemento = idFuenteElemento;
        this.idElementoTipoEspecificacion = idElementoTipoEspecificacion;
        this.valor = valor;
    }

    public Integer getIdPeriodoRecoleccion() {
        return idPeriodoRecoleccion;
    }

    public void setIdPeriodoRecoleccion(Integer idPeriodoRecoleccion) {
        this.idPeriodoRecoleccion = idPeriodoRecoleccion;
    }

    public Integer getIdFuenteElemento() {
        return idFuenteElemento;
    }

    public void setIdFuenteElemento(Integer idFuenteElemento) {
        this.idFuenteElemento = idFuenteElemento;
    }

    public Integer getIdElementoTipoEspecificacion() {
        return idElementoTipoEspecificacion;
    }

    public void setIdElementoTipoEspecificacion(Integer idElementoTipoEspecificacion) {
        this.idElementoTipoEspecificacion = idElementoTipoEspecificacion;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

}
