package gov.dane.indices.sqlite.dao;

import java.util.List;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table "ELEMENTO_ESPECIFICACION".
 */
public class ElementoEspecificacionDao  {

    public static final String TABLENAME = "ELEMENTO_ESPECIFICACION";

    

    /** Creates the underlying database table. */
    public static String createTable(boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        String result ="CREATE TABLE " + constraint + "ELEMENTO_ESPECIFICACION (" + //
                "\"ID_ELEMENTO_ESPECIFICACION\" INTEGER PRIMARY KEY ," + // 0: idElementoEspecificacion
                "\"ID_TIPO_ESPECIFICACION\" INTEGER," + // 1: idTipoEspecificacion
                "\"ID_ARGUMENTO\" INTEGER," + // 2: idArgumento
                "\"ORDEN\" INTEGER," + // 3: orden
                "\"NOMBRE_ELEMENTO\" TEXT," + // 4: nombreElemento
                "\"ID_ELEMENTO\" INTEGER NOT NULL );"; // 5: idElemento
        return result;
    }

    /** Drops the underlying database table. */
    public static String dropTable(boolean ifExists) {
        return "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "ELEMENTO_ESPECIFICACION";
     
    }

   

}
