package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CARACTERISTICA_I01".
 */
public class CaracteristicaI01 {

    private Long caraId;
    private String caraDescripcion;
    private Long tireId;
    private Long caraOrden;

    public CaracteristicaI01() {
    }

    public CaracteristicaI01(Long caraId) {
        this.caraId = caraId;
    }

    public CaracteristicaI01(Long caraId, String caraDescripcion, Long tireId, Long caraOrden) {
        this.caraId = caraId;
        this.caraDescripcion = caraDescripcion;
        this.tireId = tireId;
        this.caraOrden = caraOrden;
    }

    public Long getCaraId() {
        return caraId;
    }

    public void setCaraId(Long caraId) {
        this.caraId = caraId;
    }

    public String getCaraDescripcion() {
        return caraDescripcion;
    }

    public void setCaraDescripcion(String caraDescripcion) {
        this.caraDescripcion = caraDescripcion;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    public Long getCaraOrden() {
        return caraOrden;
    }

    public void setCaraOrden(Long caraOrden) {
        this.caraOrden = caraOrden;
    }

}
