package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "CARACTERISTICA".
 */
public class CaracteristicaDistrito  implements Serializable {

    private Long id;
    private Long caraId;
    private String caraDescripcion;
    private String vapeDescripcion;
    private Long tireId;
    private Long vapeId;

    public CaracteristicaDistrito() {
    }

    public CaracteristicaDistrito(Long caraId) {
        this.caraId = caraId;
    }

    public CaracteristicaDistrito(Long id, Long caraId, String caraDescripcion, Long tireId, Long vapeId, String vapeDescripcion) {
        this.id = id;
        this.caraId = caraId;
        this.caraDescripcion = caraDescripcion;
        this.tireId = tireId;
        this.vapeId = vapeId;
        this.vapeDescripcion = vapeDescripcion;
    }

    public Long getCaraId() {
        return caraId;
    }

    public void setCaraId(Long caraId) {
        this.caraId = caraId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCaraDescripcion() {
        return caraDescripcion;
    }

    public void setCaraDescripcion(String caraDescripcion) {
        this.caraDescripcion = caraDescripcion;
    }

    public String getVapeDescripcion() {
        return vapeDescripcion;
    }

    public void setVapeDescripcion(String vapeDescripcion) {
        this.vapeDescripcion = vapeDescripcion;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    public Long getVapeId() {
        return vapeId;
    }

    public void setVapeId(Long vapeId) {
        this.vapeId = vapeId;
    }

    @Override
    public String toString() {
        return vapeDescripcion;
    }
}
