package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONFIGURACION".
 */
public class Configuracion {

    private Long id;
    private boolean transmisionLocal;

    public Configuracion() {
    }

    public Configuracion(Long id) {
        this.id = id;
    }

    public Configuracion(Long id, boolean transmisionLocal) {
        this.id = id;
        this.transmisionLocal = transmisionLocal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean getTransmisionLocal() {
        return transmisionLocal;
    }

    public void setTransmisionLocal(boolean transmisionLocal) {
        this.transmisionLocal = transmisionLocal;
    }

}
