package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COORDENADA".
 */
public class Coordenada {

    private Long id;
    private Long p_id_fuente;
    private Double p_longitud_gps;
    private Double p_latitud_gps;
    private Double p_altitud_gps;
    private Double p_precision_gps;
    private Double p_longitud_dmc;
    private Double p_latitud_dmc;
    private Double p_altitud_dmc;
    private Double p_precision_dmc;

    public Coordenada() {
    }

    public Coordenada(Long id) {
        this.id = id;
    }

    public Coordenada(Long id, Long p_id_fuente, Double p_longitud_gps, Double p_latitud_gps, Double p_altitud_gps, Double p_precision_gps, Double p_longitud_dmc, Double p_latitud_dmc, Double p_altitud_dmc, Double p_precision_dmc) {
        this.id = id;
        this.p_id_fuente = p_id_fuente;
        this.p_longitud_gps = p_longitud_gps;
        this.p_latitud_gps = p_latitud_gps;
        this.p_altitud_gps = p_altitud_gps;
        this.p_precision_gps = p_precision_gps;
        this.p_longitud_dmc = p_longitud_dmc;
        this.p_latitud_dmc = p_latitud_dmc;
        this.p_altitud_dmc = p_altitud_dmc;
        this.p_precision_dmc = p_precision_dmc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getP_id_fuente() {
        return p_id_fuente;
    }

    public void setP_id_fuente(Long p_id_fuente) {
        this.p_id_fuente = p_id_fuente;
    }

    public Double getP_longitud_gps() {
        return p_longitud_gps;
    }

    public void setP_longitud_gps(Double p_longitud_gps) {
        this.p_longitud_gps = p_longitud_gps;
    }

    public Double getP_latitud_gps() {
        return p_latitud_gps;
    }

    public void setP_latitud_gps(Double p_latitud_gps) {
        this.p_latitud_gps = p_latitud_gps;
    }

    public Double getP_altitud_gps() {
        return p_altitud_gps;
    }

    public void setP_altitud_gps(Double p_altitud_gps) {
        this.p_altitud_gps = p_altitud_gps;
    }

    public Double getP_precision_gps() {
        return p_precision_gps;
    }

    public void setP_precision_gps(Double p_precision_gps) {
        this.p_precision_gps = p_precision_gps;
    }

    public Double getP_longitud_dmc() {
        return p_longitud_dmc;
    }

    public void setP_longitud_dmc(Double p_longitud_dmc) {
        this.p_longitud_dmc = p_longitud_dmc;
    }

    public Double getP_latitud_dmc() {
        return p_latitud_dmc;
    }

    public void setP_latitud_dmc(Double p_latitud_dmc) {
        this.p_latitud_dmc = p_latitud_dmc;
    }

    public Double getP_altitud_dmc() {
        return p_altitud_dmc;
    }

    public void setP_altitud_dmc(Double p_altitud_dmc) {
        this.p_altitud_dmc = p_altitud_dmc;
    }

    public Double getP_precision_dmc() {
        return p_precision_dmc;
    }

    public void setP_precision_dmc(Double p_precision_dmc) {
        this.p_precision_dmc = p_precision_dmc;
    }

}
