package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ENVIO_ARTI_CARA_VALORES_I01".
 */
public class EnvioArtiCaraValoresI01 {

    private Long grin2Id;
    private Long futiId;
    private Long tireId;
    private Long caraId;
    private Long artiId;
    private Long vapeId;
    private String vapeDescripcion;

    public EnvioArtiCaraValoresI01() {
    }

    public EnvioArtiCaraValoresI01(Long grin2Id) {
        this.grin2Id = grin2Id;
    }

    public EnvioArtiCaraValoresI01(Long grin2Id, Long futiId, Long tireId, Long caraId, Long artiId, Long vapeId, String vapeDescripcion) {
        this.grin2Id = grin2Id;
        this.futiId = futiId;
        this.tireId = tireId;
        this.caraId = caraId;
        this.artiId = artiId;
        this.vapeId = vapeId;
        this.vapeDescripcion = vapeDescripcion;
    }

    public Long getGrin2Id() {
        return grin2Id;
    }

    public void setGrin2Id(Long grin2Id) {
        this.grin2Id = grin2Id;
    }

    public Long getFutiId() {
        return futiId;
    }

    public void setFutiId(Long futiId) {
        this.futiId = futiId;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    public Long getCaraId() {
        return caraId;
    }

    public void setCaraId(Long caraId) {
        this.caraId = caraId;
    }

    public Long getArtiId() {
        return artiId;
    }

    public void setArtiId(Long artiId) {
        this.artiId = artiId;
    }

    public Long getVapeId() {
        return vapeId;
    }

    public void setVapeId(Long vapeId) {
        this.vapeId = vapeId;
    }

    public String getVapeDescripcion() {
        return vapeDescripcion;
    }

    public void setVapeDescripcion(String vapeDescripcion) {
        this.vapeDescripcion = vapeDescripcion;
    }

}
