package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "FUENTE_TIRE_I01".
 */
public class FuenteTireI01 implements Serializable{

    private Long id;
    private Long futiId;
    private Long fuenId;
    private Long tireId;
    private String tireNombre;
    private String muniId;
    private String muniNombre;
    private java.util.Date prreFechaProgramada;




    public FuenteTireI01() {
    }

    public FuenteTireI01(Long id) {
        this.id = id;
    }

    public FuenteTireI01(Long id, Long futiId, Long fuenId, Long tireId, String tireNombre, String muniId, String muniNombre, java.util.Date prreFechaProgramada) {
        this.id = id;
        this.futiId = futiId;
        this.fuenId = fuenId;
        this.tireId = tireId;
        this.tireNombre = tireNombre;
        this.muniId = muniId;
        this.muniNombre = muniNombre;
        this.prreFechaProgramada = prreFechaProgramada;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFutiId() {
        return futiId;
    }

    public void setFutiId(Long futiId) {
        this.futiId = futiId;
    }

    public Long getFuenId() {
        return fuenId;
    }

    public void setFuenId(Long fuenId) {
        this.fuenId = fuenId;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    public String getTireNombre() {
        return tireNombre;
    }

    public void setTireNombre(String tireNombre) {
        this.tireNombre = tireNombre;
    }

    public String getMuniId() {
        return muniId;
    }

    public void setMuniId(String muniId) {
        this.muniId = muniId;
    }

    public String getMuniNombre() {
        return muniNombre;
    }

    public void setMuniNombre(String muniNombre) {
        this.muniNombre = muniNombre;
    }

    public java.util.Date getPrreFechaProgramada() {
        return prreFechaProgramada;
    }

    public void setPrreFechaProgramada(java.util.Date prreFechaProgramada) {
        this.prreFechaProgramada = prreFechaProgramada;
    }

}
