package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GRUPO_INSUMO_I01".
 */
public class GrupoInsumoI01 {

    private Long id;

    public GrupoInsumoI01() {
    }

    public GrupoInsumoI01(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
