package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GRUPO".
 */
public class Grupo {

    private Long grupId;
    private String grupNombre;
    private Long tireId;

    public Grupo() {
    }

    public Grupo(Long grupId) {
        this.grupId = grupId;
    }

    public Grupo(Long grupId, String grupNombre, Long tireId) {
        this.grupId = grupId;
        this.grupNombre = grupNombre;
        this.tireId = tireId;
    }

    public Long getGrupId() {
        return grupId;
    }

    public void setGrupId(Long grupId) {
        this.grupId = grupId;
    }

    public String getGrupNombre() {
        return grupNombre;
    }

    public void setGrupNombre(String grupNombre) {
        this.grupNombre = grupNombre;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    @Override
    public String toString() {
        return  grupNombre;
    }
}
