package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRESENTACION".
 */
public class Presentacion {

    private Long idpresentacion;
    private String nombre;
    private java.util.Date fechaCreacion;
    private String usuarioCreacion;
    private java.util.Date fechaModificacion;
    private String usuarioModificacion;

    public Presentacion() {
    }

    public Presentacion(Long idpresentacion) {
        this.idpresentacion = idpresentacion;
    }

    public Presentacion(Long idpresentacion, String nombre, java.util.Date fechaCreacion, String usuarioCreacion, java.util.Date fechaModificacion, String usuarioModificacion) {
        this.idpresentacion = idpresentacion;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.usuarioCreacion = usuarioCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
    }

    public Long getIdpresentacion() {
        return idpresentacion;
    }

    public void setIdpresentacion(Long idpresentacion) {
        this.idpresentacion = idpresentacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public java.util.Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(java.util.Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getUsuarioCreacion() {
        return usuarioCreacion;
    }

    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    public java.util.Date getFechaModificacion() {
        return fechaModificacion;
    }

    public void setFechaModificacion(java.util.Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public String getUsuarioModificacion() {
        return usuarioModificacion;
    }

    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

}
