package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRINCIPAL".
 */
public class Principal {

    private Long id;
    private Long artiVlrMinDiasm;
    private Long futiId;
    private String novedadAnterior;
    private Long articacoId;
    private String subgNombre;
    private String unmeNombre2;
    private String cacoNombre;
    private String fuenNombre;
    private String articacoRegicaLinea;
    private Long tiprId;
    private String artiNombre;
    private Long artiVlrMaxTomas;
    private String tiprNombre;
    private String unmeNombrePpal;
    private Long artiVlrMinRondas;
    private Long promAntDiario;
    private Long artiVlrMinTomas;
    private Long artiVlrMaxRondas;
    private java.util.Date prreFechaProgramada;
    private String muniId;
    private Long unmeCantidad2;
    private String grupNombre;
    private Long unmeCantidadPpal;
    private Long artiVlrMaxDiasm;
    private Long unmeId;
    private Long tireId;
    private Long fuenId;
    private Long artiId;
    private Long cacoId;

    public Principal() {
    }

    public Principal(Long id) {
        this.id = id;
    }

    public Principal(Long id, Long artiVlrMinDiasm, Long futiId, String novedadAnterior, Long articacoId, String subgNombre, String unmeNombre2, String cacoNombre, String fuenNombre, String articacoRegicaLinea, Long tiprId, String artiNombre, Long artiVlrMaxTomas, String tiprNombre, String unmeNombrePpal, Long artiVlrMinRondas, Long promAntDiario, Long artiVlrMinTomas, Long artiVlrMaxRondas, java.util.Date prreFechaProgramada, String muniId, Long unmeCantidad2, String grupNombre, Long unmeCantidadPpal, Long artiVlrMaxDiasm, Long unmeId, Long tireId, Long fuenId, Long artiId, Long cacoId) {
        this.id = id;
        this.artiVlrMinDiasm = artiVlrMinDiasm;
        this.futiId = futiId;
        this.novedadAnterior = novedadAnterior;
        this.articacoId = articacoId;
        this.subgNombre = subgNombre;
        this.unmeNombre2 = unmeNombre2;
        this.cacoNombre = cacoNombre;
        this.fuenNombre = fuenNombre;
        this.articacoRegicaLinea = articacoRegicaLinea;
        this.tiprId = tiprId;
        this.artiNombre = artiNombre;
        this.artiVlrMaxTomas = artiVlrMaxTomas;
        this.tiprNombre = tiprNombre;
        this.unmeNombrePpal = unmeNombrePpal;
        this.artiVlrMinRondas = artiVlrMinRondas;
        this.promAntDiario = promAntDiario;
        this.artiVlrMinTomas = artiVlrMinTomas;
        this.artiVlrMaxRondas = artiVlrMaxRondas;
        this.prreFechaProgramada = prreFechaProgramada;
        this.muniId = muniId;
        this.unmeCantidad2 = unmeCantidad2;
        this.grupNombre = grupNombre;
        this.unmeCantidadPpal = unmeCantidadPpal;
        this.artiVlrMaxDiasm = artiVlrMaxDiasm;
        this.unmeId = unmeId;
        this.tireId = tireId;
        this.fuenId = fuenId;
        this.artiId = artiId;
        this.cacoId = cacoId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getArtiVlrMinDiasm() {
        return artiVlrMinDiasm;
    }

    public void setArtiVlrMinDiasm(Long artiVlrMinDiasm) {
        this.artiVlrMinDiasm = artiVlrMinDiasm;
    }

    public Long getFutiId() {
        return futiId;
    }

    public void setFutiId(Long futiId) {
        this.futiId = futiId;
    }

    public String getNovedadAnterior() {
        return novedadAnterior;
    }

    public void setNovedadAnterior(String novedadAnterior) {
        this.novedadAnterior = novedadAnterior;
    }

    public Long getArticacoId() {
        return articacoId;
    }

    public void setArticacoId(Long articacoId) {
        this.articacoId = articacoId;
    }

    public String getSubgNombre() {
        return subgNombre;
    }

    public void setSubgNombre(String subgNombre) {
        this.subgNombre = subgNombre;
    }

    public String getUnmeNombre2() {
        return unmeNombre2;
    }

    public void setUnmeNombre2(String unmeNombre2) {
        this.unmeNombre2 = unmeNombre2;
    }

    public String getCacoNombre() {
        return cacoNombre;
    }

    public void setCacoNombre(String cacoNombre) {
        this.cacoNombre = cacoNombre;
    }

    public String getFuenNombre() {
        return fuenNombre;
    }

    public void setFuenNombre(String fuenNombre) {
        this.fuenNombre = fuenNombre;
    }

    public String getArticacoRegicaLinea() {
        return articacoRegicaLinea;
    }

    public void setArticacoRegicaLinea(String articacoRegicaLinea) {
        this.articacoRegicaLinea = articacoRegicaLinea;
    }

    public Long getTiprId() {
        return tiprId;
    }

    public void setTiprId(Long tiprId) {
        this.tiprId = tiprId;
    }

    public String getArtiNombre() {
        return artiNombre;
    }

    public void setArtiNombre(String artiNombre) {
        this.artiNombre = artiNombre;
    }

    public Long getArtiVlrMaxTomas() {
        return artiVlrMaxTomas;
    }

    public void setArtiVlrMaxTomas(Long artiVlrMaxTomas) {
        this.artiVlrMaxTomas = artiVlrMaxTomas;
    }

    public String getTiprNombre() {
        return tiprNombre;
    }

    public void setTiprNombre(String tiprNombre) {
        this.tiprNombre = tiprNombre;
    }

    public String getUnmeNombrePpal() {
        return unmeNombrePpal;
    }

    public void setUnmeNombrePpal(String unmeNombrePpal) {
        this.unmeNombrePpal = unmeNombrePpal;
    }

    public Long getArtiVlrMinRondas() {
        return artiVlrMinRondas;
    }

    public void setArtiVlrMinRondas(Long artiVlrMinRondas) {
        this.artiVlrMinRondas = artiVlrMinRondas;
    }

    public Long getPromAntDiario() {
        return promAntDiario;
    }

    public void setPromAntDiario(Long promAntDiario) {
        this.promAntDiario = promAntDiario;
    }

    public Long getArtiVlrMinTomas() {
        return artiVlrMinTomas;
    }

    public void setArtiVlrMinTomas(Long artiVlrMinTomas) {
        this.artiVlrMinTomas = artiVlrMinTomas;
    }

    public Long getArtiVlrMaxRondas() {
        return artiVlrMaxRondas;
    }

    public void setArtiVlrMaxRondas(Long artiVlrMaxRondas) {
        this.artiVlrMaxRondas = artiVlrMaxRondas;
    }

    public java.util.Date getPrreFechaProgramada() {
        return prreFechaProgramada;
    }

    public void setPrreFechaProgramada(java.util.Date prreFechaProgramada) {
        this.prreFechaProgramada = prreFechaProgramada;
    }

    public String getMuniId() {
        return muniId;
    }

    public void setMuniId(String muniId) {
        this.muniId = muniId;
    }

    public Long getUnmeCantidad2() {
        return unmeCantidad2;
    }

    public void setUnmeCantidad2(Long unmeCantidad2) {
        this.unmeCantidad2 = unmeCantidad2;
    }

    public String getGrupNombre() {
        return grupNombre;
    }

    public void setGrupNombre(String grupNombre) {
        this.grupNombre = grupNombre;
    }

    public Long getUnmeCantidadPpal() {
        return unmeCantidadPpal;
    }

    public void setUnmeCantidadPpal(Long unmeCantidadPpal) {
        this.unmeCantidadPpal = unmeCantidadPpal;
    }

    public Long getArtiVlrMaxDiasm() {
        return artiVlrMaxDiasm;
    }

    public void setArtiVlrMaxDiasm(Long artiVlrMaxDiasm) {
        this.artiVlrMaxDiasm = artiVlrMaxDiasm;
    }

    public Long getUnmeId() {
        return unmeId;
    }

    public void setUnmeId(Long unmeId) {
        this.unmeId = unmeId;
    }

    public Long getTireId() {
        return tireId;
    }

    public void setTireId(Long tireId) {
        this.tireId = tireId;
    }

    public Long getFuenId() {
        return fuenId;
    }

    public void setFuenId(Long fuenId) {
        this.fuenId = fuenId;
    }

    public Long getArtiId() {
        return artiId;
    }

    public void setArtiId(Long artiId) {
        this.artiId = artiId;
    }

    public Long getCacoId() {
        return cacoId;
    }

    public void setCacoId(Long cacoId) {
        this.cacoId = cacoId;
    }

}
