package gov.dane.sipsa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECOLECCION_I01".
 */
public class RecoleccionI01 {

    private Long id;
    private Long futiId;
    private Long artiId;
    private Long grin2Id;
    private Long infoId;
    private String infoNombre;
    private String infoTelefono;
    private java.util.Date fechaProgramada;
    private Double precioActual;
    private java.util.Date fechaRecoleccion;
    private String desviacion;
    private Long observacionId;
    private String observaciones;
    private String novedad;
    private Double precioAnterior;
    private Integer estado_transmitido;

    public RecoleccionI01() {
    }

    public RecoleccionI01(Long id) {
        this.id = id;
    }

    public RecoleccionI01(Long id, Long futiId, Long artiId, Long grin2Id, Long infoId, String infoNombre, String infoTelefono, java.util.Date fechaProgramada, Double precioActual, java.util.Date fechaRecoleccion, String desviacion, Long observacionId, String observaciones, String novedad, Double precioAnterior, Integer estado_transmitido) {
        this.id = id;
        this.futiId = futiId;
        this.artiId = artiId;
        this.grin2Id = grin2Id;
        this.infoId = infoId;
        this.infoNombre = infoNombre;
        this.infoTelefono = infoTelefono;
        this.fechaProgramada = fechaProgramada;
        this.precioActual = precioActual;
        this.fechaRecoleccion = fechaRecoleccion;
        this.desviacion = desviacion;
        this.observacionId = observacionId;
        this.observaciones = observaciones;
        this.novedad = novedad;
        this.precioAnterior = precioAnterior;
        this.estado_transmitido = estado_transmitido;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFutiId() {
        return futiId;
    }

    public void setFutiId(Long futiId) {
        this.futiId = futiId;
    }

    public Long getArtiId() {
        return artiId;
    }

    public void setArtiId(Long artiId) {
        this.artiId = artiId;
    }

    public Long getGrin2Id() {
        return grin2Id;
    }

    public void setGrin2Id(Long grin2Id) {
        this.grin2Id = grin2Id;
    }

    public Long getInfoId() {
        return infoId;
    }

    public void setInfoId(Long infoId) {
        this.infoId = infoId;
    }

    public String getInfoNombre() {
        return infoNombre;
    }

    public void setInfoNombre(String infoNombre) {
        this.infoNombre = infoNombre;
    }

    public String getInfoTelefono() {
        return infoTelefono;
    }

    public void setInfoTelefono(String infoTelefono) {
        this.infoTelefono = infoTelefono;
    }

    public java.util.Date getFechaProgramada() {
        return fechaProgramada;
    }

    public void setFechaProgramada(java.util.Date fechaProgramada) {
        this.fechaProgramada = fechaProgramada;
    }

    public Double getPrecioActual() {
        return precioActual;
    }

    public void setPrecioActual(Double precioActual) {
        this.precioActual = precioActual;
    }

    public java.util.Date getFechaRecoleccion() {
        return fechaRecoleccion;
    }

    public void setFechaRecoleccion(java.util.Date fechaRecoleccion) {
        this.fechaRecoleccion = fechaRecoleccion;
    }

    public String getDesviacion() {
        return desviacion;
    }

    public void setDesviacion(String desviacion) {
        this.desviacion = desviacion;
    }

    public Long getObservacionId() {
        return observacionId;
    }

    public void setObservacionId(Long observacionId) {
        this.observacionId = observacionId;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getNovedad() {
        return novedad;
    }

    public void setNovedad(String novedad) {
        this.novedad = novedad;
    }

    public Double getPrecioAnterior() {
        return precioAnterior;
    }

    public void setPrecioAnterior(Double precioAnterior) {
        this.precioAnterior = precioAnterior;
    }

    public Integer getEstado_transmitido() {
        return estado_transmitido;
    }

    public void setEstado_transmitido(Integer estado_transmitido) {
        this.estado_transmitido = estado_transmitido;
    }

}
